Repository xaviachristi/earthquake-monitor, pull requests merged in 2025-06, with the labels that each got.

#12 [PR] Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#13 [PR] Create Repository Templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/improvement.md
  .github/ISSUE_TEMPLATE/task.md
  .github/pull_request_template.md
Labels: enhancement

#68 [PR] Add dashboard wireframes.
  dashboard/wireframe.md
  dashboard/wireframe_imgs/gdpr.png
  dashboard/wireframe_imgs/historic.png
  dashboard/wireframe_imgs/home.png
  dashboard/wireframe_imgs/realtime.png
  dashboard/wireframe_imgs/reports.png
  dashboard/wireframe_imgs/subscribe.png
Labels: documentation

#66 [PR] Create MVP
  planning/mvp.md
Labels: documentation

#69 [PR] Added ERD
  architecture/erd.png
Labels: enhancement

#78 [PR] Add dashboard deploy scripts.
  dashboard/connect_ec2.sh
  dashboard/deploy_dashboard.sh
  dashboard/run_dashboard.sh
Labels: enhancement

#79 [PR] Create schema and seeding script.
  architecture/create_schema.sh
  architecture/schema.sql
  architecture/seed_data.sql
Labels: enhancement

#91 [PR] Add Alert Creation
  notifications/README.md
  notifications/conftest.py
  notifications/fake_alert.html
  notifications/lambda_handler.py
  notifications/make_html.py
  notifications/notification.md
  notifications/notification_maker.py
  notifications/requirements.txt
  notifications/test_notification_maker.py
  requirements.txt
Labels: enhancement

#95 [PR] Deploy Notification Code
  notifications/Dockerfile
  notifications/docker_notification_build.sh
  notifications/notification_lambda.py
  notifications/notification_maker.py
Labels: enhancement

#97 [PR] Added report outline
  report/report-outline.png
Labels: enhancement

#127 [PR] Update Schema and Pipeline for new table.
  architecture/schema.sql
  architecture/seed_data.sql
  pipeline/load.py
  pipeline/pipeline.py
  pipeline/test_load.py
  pipeline/transform.py
Labels: bug

#146 [PR] Finalise Dashboard Visualisations
  dashboard/Home.py
  dashboard/charts.py
  dashboard/data.py
  dashboard/pages/1_Historic.py
  dashboard/pages/1_USA.py
  dashboard/pages/2_International.py
  dashboard/pages/2_Recent.py
  dashboard/pages/3_Subscribe.py
  dashboard/requirements.txt
  requirements.txt
Labels: bug, enhancement

#149 [PR] Implement Subscription Logic
  dashboard/README.md
  dashboard/pages/3_Subscribe.py
  dashboard/requirements.txt
  dashboard/subscription.py
  dashboard/test_subscription.py
  notifications/notification_lambda.py
  notifications/notification_maker.py
Labels: enhancement

#150 [PR] Improve Pipeline
  architecture/schema.sql
  pipeline/Dockerfile
  pipeline/extract.py
  pipeline/load.py
  pipeline/pipeline.py
  pipeline/test_topic.py
  pipeline/topic.py
  pipeline/transform.py
Labels: bug, improvement

#156 [PR] Polish Dashboard
  dashboard/.streamlit/config.toml
  dashboard/Home.py
  dashboard/README.md
  dashboard/charts.py
  dashboard/connect_ec2.sh
  dashboard/data.py
  dashboard/deploy_dashboard.sh
  dashboard/earthquake_monitor.ico
  dashboard/earthquake_monitor.png
  dashboard/pages/1_USA.py
  dashboard/pages/2_International.py
  dashboard/pages/3_Subscribe.py
  dashboard/pages/4_Reports.py
  dashboard/pages/5_GDPR.py
  dashboard/report.py
  dashboard/run_dashboard.sh
  dashboard/subscription.py
  dashboard/test_subscription.py
Labels: bug, documentation, improvement

#159 [PR] Pipeline tests.
  api/test_app.py
  dashboard/conftest.py
  dashboard/test_charts.py
  pipeline/pipeline.py
  pipeline/test_pipeline.py
  pipeline/test_topic.py
  report/main.py
  report/test_main.py
Labels: enhancement

#73 [PR] Added Architecture Diagram
  architecture/architecture-diagram.png
Labels: enhancement

#164 [PR] Write top-level README
  .DS_Store
  README.md
  earthquake_monitor.png
Labels: documentation

#165 [PR] Updated architecture diagram with changes
  architecture/architecture-diagram.png
  architecture/earthquake-architecture-friday-final.png
Labels: documentation
